markdown: kramdown
pygments: true

title: George Sudarkoff
tagline: Blogged Et Animam Levavi

url: http://george.sudarkoff.com

permalink: /:title 

author:
    name: George Sudarkoff
    email: george@sudarkoff.com
    github: sudarkoff
    twitter: sudarkoff
    gravatar: https://en.gravatar.com/userimage/3132027/98aa8619da8b3bc99448e6d9837e5545.jpg

comments:
    provider: disqus
    disqus:
        short_name : georgesudarkoff

analytics:
    provider: google
    google:
        tracking_id: 'UA-101017-1'
        domain: 'george.sudarkoff.com'

